fast:
    flowable:
        enabled: true
    demoMode:
        enabled: false
        post: 'edit,del,remove,clean,updateAvatar,updateUser,add,resetPwd,updatePass,genCode,uploadLic,status,insertAuthRoles'
        get: 'del,remove,clean,dirTreeData'
        urlPatterns: '/sys/*,/tool/*,/file/ueditor/*,/bpm/procdef/*,/bpm/model/*,/bpm/processInstance/*,/gen/test/*'
        ip:
    ssl:
        enabled: true
    encrypt:
        key:
    xss:
        enabled: true
        excludes: /sys/notice/*,/sys/database/add
        urlPatterns: /sys/*,/tool/*
    csrf:
        enabled: true
    jta:
        enabled: true
license:
    subject: fastOS
    publicAlias: j2eefastCert
    storePass: j2eefast.com
    licensePath: license/license.lic
    publicKeysStorePath: license/publicCerts.keystore

    privateAlias:
    keyPass:
    privateKeysStorePath:

spring:
    datasource:
        master:
            driverClassName: com.mysql.cj.jdbc.Driver
            url:
            username:
            password:
            filters: mergeStat
        flowable:
            driverClassName:
            url:
            username:
            password:
            filters:
    redis:
        database: 10
        host:
        port:
        password:
        timeout: 6000ms
        jedis:
            pool:
                max-active: 1000
                max-wait: -1ms
                max-idle: 10
                min-idle: 5
    rabbitmq:
        addresses: ip:5672
        username:
        password:
        virtual-host: /
        publisher-confirms: true
        publisher-returns: true
        template.mandatory: true
        listener:
            simple:
                concurrency: 5
                max-concurrency: 10
                acknowledge-mode: manual
                prefetch: 1
mybatis-plus:
    type-aliases-package: com.j2eefast.*.*.entity
    mapper-package: com.j2eefast.*.*.mapper

http:
    port: 80
server:
    name: '##################J2eeFAST[生产环境]##############'
    projectName: 'J2eeFAST[生产环境]'
    port: 443 #HTTPS端口