# 设置项目访问路径
#server:
#    servlet:
#        context-path: /

spring:
    # 启动环境 Dev|Test|Prod
    profiles:
        active: Dev
    freemarker:
        #模板引擎缓存
        cache: true

#登录安全验证基本配置
aj:
   captcha:
      #redis 缓存 本地缓存 local
      cache-type: redis

# Shiro 配置
shiro:
#    cookie:
#        # 设置Cookie的域名 默认空，即当前访问的域名
#        domain:
#        # 设置HttpOnly属性
#        httpOnly: true
#        # 设置Cookie的过期时间，天为单位
#        maxAge: 30
#    session:
#        # Session超时时间，-1代表永不过期（默认30分钟）
#        expireTime: 30
#        #设置session失效的扫描时间, 清理用户直接关闭浏览器造成的孤立会话 (默认设置5分钟)
#        validationTime: 5
    rememberMe:
         # 是否开启记住我
         enabled: true
         # 若开启记住我请设置记住我密钥 可以在 com.j2eefast.test.EncondeTest 测试类 执行getShiroDeskey单元测试方法 获取项目唯一密钥
         # 若不设置，则每次启动系统后自动随机生成一个新秘钥，这样会导致每次重启后，客户端记录的用户信息将失效。
         cipherKey: 6OLU0Aarr/mQ4tkxEzMZ5A==
    #custome url filter Map(系统权限拦截配置)   
    filterMap: "{
           '/login': 'anon',
           '/auth/**': 'anon',
           '/404.html': 'anon',
           '/upbw/**': 'anon'
           }"

#mybatis 配置
mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml

#日志路径配置
#logging:
#    file:
#        name: fast
#        path: logs/

logging:
  pattern:
    console: "%date{HH:mm:ss.SSS} %-5level %-30.30logger{29} : %msg%n"
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG