spring:
    #数据库配置
    datasource:
        #默认(主)数据库配置
        master:
            #mysql 数据库配置
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://192.168.20.110:3306/fastdb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
            #url: ENC{6mrUX1SZ/wgmN11iXmMyqplOpIbLBTlo3wh3K7T9qieephrFWPxUeOeswsLG+HKDvzd1wbo0DONij81tZUjIIEX/2gADAjSoJewZaxIeuVD1foEoEjzB/US3uf3gJYkee3IJPFEhABPSefwJGthT4xceWx27axifRKC6SfDzl5A=}
            username: fast
            password: fast@123$
            filters: mergeStat

            #PostgreSql 数据库配置
            #driverClassName: org.postgresql.Driver
            #url: jdbc:postgresql://192.168.20.110:5432/fastdb
            #username: fast
            #password: fast@123$
            #filters: mergeStat

            #oracle 数据库配置
            #driverClassName: oracle.jdbc.driver.OracleDriver
            #url: jdbc:oracle:thin:@192.168.1.127:8080/orcl
            #username: fastdb
            #password: fastdb@123$
            #filters: wall,mergeStat

            #mssql 2012以上版本 数据库配置
            #driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
            #url: jdbc:sqlserver://ip:端口;database=fastdb
            #username: fastdb
            #password: fastdb@123$
            #filters: wall,mergeStat

    #redis数据库服务器
    redis:
        database: 10
        host: 192.168.20.110
        port: 6379
        #redis密码 请为你的redis 设置连接密码、 如果无密码、请注释 #password,否则会报连接异常
        password: 123456

mybatis-plus:
    #实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: com.j2eefast.*.*.entity
    #扫描mapper 相当于 @MapperScan 注解,多个逗号分割
    mapper-package: com.j2eefast.*.*.mapper
    #打印sql语句,调试用
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
http:
  #port: 8200 #web端口
  #port: 80 #web端口
server:
    name: '##################J2eeFAST[开发环境]##############'
    projectName: 'J2eeFAST[开发环境]'
    port: 8080 #HTTPS端口
    #port: 443 #HTTPS端口