spring:
    datasource:
        #默认(主)数据库配置
        master:
            driverClassName:
            url:
            username:
            password:
            filters: mergeStat
    #redis数据库服务器
    redis:
        database: 10
        host:
        port: 6379
        #redis密码 请为你的redis 设置连接密码、 如果无密码、请注释 #password,否则会报连接异常
        password:

mybatis-plus:
    #实体扫描，多个package用逗号或者分号分隔
    type-aliases-package: com.j2eefast.*.*.entity
    #扫描mapper 相当于 @MapperScan 注解,多个逗号分割
    mapper-package: com.j2eefast.*.*.mapper
    #打印sql语句,调试用
    configuration:
       log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
http:
    #port: 8200 #web端口
    #port: 80 #web端口
server:
    name: '##################J2eeFAST[测试环境]##############'
    projectName: 'J2eeFAST[测试环境]'
    port: 8080 #HTTPS端口
    #port: 443 #HTTPS端口